### ISSUE TITLE
[BUG]: Pressure decimal place wrong

### ISSUE THREAD

**Issue by jmcc94** [bitfocus/companion-module-openweather-rest#12]
In the pressure variable. it looks like the decimal place is in the wrong place..

Currently on openweather, the pressure for my location reads as 1021hPa... converting to mmHg is 765... the variable show 7.65

Looking in the code, it looks like the conversion is done correctly, then the result is divided again by 100.

Also - would it be possible to get the variable in hPa, without the conversion

**Comment by istnv** [comment]
Wow! Someone else that uses this module!
I also added variables for the rest of the Imperial and Metric conversions.
